# TF-IDF Analyze


# Dataset

There are 10 sentences to create word vectors

In [1]:
import pandas as pd
import numpy as np

In [2]:
mylist = []
for i in range(1,10):
    df = pd.read_csv('Expressions%d.csv' %i ,header = None)
    list_2d= df.values.tolist()
    globals()['category'+str(i)] = np.concatenate(list_2d).tolist()
    mylist.append(np.concatenate(list_2d).tolist())
    
mylist[5]

['갈리다',
 '고되다',
 '근육통',
 '기분이 안 느껴진다',
 '기운이 없다',
 '나무늘보',
 '나른하다',
 '납덩이',
 '누워있다',
 '늘어지다',
 '몸이 둔하다',
 '몸이 무겁다',
 '번아웃',
 '빡세다',
 '소진',
 '쉬고 싶다',
 '쑤시다',
 '어깨가 쳐지다',
 '움직이기 힘들다',
 '집 밖에 나가기 싫다',
 '찌뿌둥',
 '처지다',
 '컨디션이 나쁘다',
 '피곤',
 '피로',
 '힘이 없다']

In [3]:
raw_docs = []

for i in range(9):
    raw_docs.append(" ".join(mylist[i]))
    
raw_docs

['가망이 없다 가슴 아프다 가치 없다 갇힌 것 같다 갑갑하다 고통스럽다 공허하다 괴롭다 기대할 것이 없다 기분이 가라앉는다 기분이 나쁘다 기분이 별로다 기분이 안좋다 기분이 처진다 꿀꿀하다 끔찍하다 끝장 나락 눈물 단념 답답하다 더 내려갈 데가 없다 마음 아프다 막다른 느낌 막막하다 망하다 무의미하다 바닥까지 내려간다 방법이 없다 방향을 잃다 부질없다 불편 불행 비참 살기 싫다 생각하기도 싫다 센치하다 속상하다 슬프다 실패 앞이 캄캄하다 외롭다.  우울하다 울고싶다 울적하다 이생망 저주받았다 절망 좌절 죽고 싶다 죽을 맛이다 지옥같다 체념 침울 포기 할 수 없다 행복하지 않다 희망이 없다 힘들다',
 '가라앉다 감정이 안 느껴진다 감흥 없다 관심 없다 관심이 줄다 귀찮다 그만두다 나가기 싫다 노관심 노잼 누워 있다 덧 없다 될대로 되라 때려치다 만나기 귀찮다 무관심 무기력 무의미 부질 없다 생각 없다 소용 없다 시무룩 신경 쓰지 않는다 신이 안난다 싫증 안 하려 하다 억지로 하다 욕구가 준다 움직이기 싫다 의욕없다 일하기 힘들다 재미 없다 즐겁지 않다 지루하다 지친다  집에만 있다 처진다 퇴사 포기 피곤 피하다 하기 싫다 할수 없다 흥미 없다 힘들다',
 '굶다 꾸역꾸역 끼니를 거르다 다이어트 더부룩하다. 돼지 또 먹어버렸다 뚱뚱하다 마르다 많이 먹다 말랐다 맛을 모르겠다 맛이 없다 먹기 귀찮다 먹기 싫다 먹토했다 몸무게 몸이 불었다 미식거리다 배가 빵빵하다 배가 안 고프다 배를 채우다 비만 살이 붙다 살이 빠지다 살이 찌다 소화가 안 된다 소화불량 식욕 제어가 안된다 식욕 터진다 식욕이 늘다 식욕이 없다 식욕이 줄다 식탐 억지로 먹는다 옷이 맞지 않는다 옷이 헐렁해졌다 음식이 땡긴다 입 맛 없다 입 터졌다 입맛이 늘다 쳐먹다 토하다 폭식',
 '깊게 못 잔다 꾸벅꾸벅 졸다 눈꺼풀이 무겁다 눈만 감고 있다 늦게 일어난다 다시 자기 힘들다 뒤척거린다 뜬 눈으로 지새다 말똥말똥 못 일어나다 못 자다 밤을 새다 불면 불면증 새벽에 깨다 수면장애 수면제 신생아처럼 

# Morpheme Analysis in Korean - Konlpy

In [4]:
from konlpy.tag import Okt

okt = Okt()
corpus = []

for i in range(9):
    temp = []
    for expression in mylist[i]:
        temp+=okt.morphs(expression)
    corpus.append(temp)

                            
corpus[0]

['가망',
 '이',
 '없다',
 '가슴',
 '아프다',
 '가치',
 '없다',
 '갇힌',
 '것',
 '같다',
 '갑갑하다',
 '고통스럽다',
 '공허하다',
 '괴롭다',
 '기대할',
 '것',
 '이',
 '없다',
 '기분',
 '이',
 '가라앉는다',
 '기분',
 '이',
 '나쁘다',
 '기분',
 '이',
 '별로',
 '다',
 '기분',
 '이',
 '안좋다',
 '기분',
 '이',
 '처진다',
 '꿀꿀하다',
 '끔찍하다',
 '끝장',
 '나락',
 '눈물',
 '단념',
 '답답하다',
 '더',
 '내려갈',
 '데',
 '가',
 '없다',
 '마음',
 '아프다',
 '막',
 '다른',
 '느낌',
 '막막하다',
 '망하다',
 '무의미하다',
 '바닥',
 '까지',
 '내려간다',
 '방법',
 '이',
 '없다',
 '방향',
 '을',
 '잃다',
 '부질없다',
 '불편',
 '불행',
 '비참',
 '살기',
 '싫다',
 '생각',
 '하기도',
 '싫다',
 '센치하다',
 '속상하다',
 '슬프다',
 '실패',
 '앞',
 '이',
 '캄캄하다',
 '외롭다',
 '.',
 '우울하다',
 '울고싶다',
 '울적하다',
 '이생',
 '망',
 '저주받았다',
 '절망',
 '좌절',
 '죽고',
 '싶다',
 '죽',
 '을',
 '맛',
 '이다',
 '지옥',
 '같다',
 '체념',
 '침울',
 '포기',
 '할',
 '수',
 '없다',
 '행복하지',
 '않다',
 '희망이',
 '없다',
 '힘들다']

# Remove Stop Words 

    * Stop words: set of commonly used words in any language
    
    In order for effiency of creating word vector, we will remove commonly used words.



In [11]:
stopwords = ['의','가','을','이','은','들','는','좀','걍','과','도','를','으로','자','에','에만','와','한','하다','에게','.'
             ,'것','갈리','데','다','고','지','에서','']

docs = []
for i in range(9):
    for word in corpus[i]: 
        if word in stopwords:
                corpus[i].remove(word)
    docs.append(" ".join(corpus[i]))

for i in range(9):
    for word in corpus[i]:
        if len(word) == 1:
            corpus[i].remove(word)
#         docs.append(" ".join(corpus[i]))
        
for i in range(1,10):
    print("group"+str(i))
    print(docs[i-1])
    print("      ")

group1
가망 없다 가슴 아프다 가치 없다 갇힌 같다 갑갑하다 고통스럽다 공허하다 괴롭다 기대할 없다 기분 가라앉는다 기분 나쁘다 기분 별로 기분 안좋다 기분 처진다 꿀꿀하다 끔찍하다 끝장 나락 눈물 단념 답답하다 내려갈 없다 마음 아프다 다른 느낌 막막하다 망하다 무의미하다 바닥 까지 내려간다 방법 없다 방향 잃다 부질없다 불편 불행 비참 살기 싫다 생각 하기도 싫다 센치하다 속상하다 슬프다 실패 캄캄하다 외롭다 우울하다 울고싶다 울적하다 이생 저주받았다 절망 좌절 죽고 싶다 이다 지옥 같다 체념 침울 포기 없다 행복하지 않다 희망이 없다 힘들다
      
group2
가라앉다 감정 느껴진다 감흥 없다 관심 없다 관심 줄다 귀찮다 그만두다 나가기 싫다 관심 노잼 누워 있다 없다 될대로 되라 때려치다 만나기 귀찮다 무관심 무기 무의미 부질 없다 생각 없다 소용 없다 시무 신경 쓰지 않는다 난다 싫증 하려 억지로 욕구 준다 움직이기 싫다 의욕 없다 하기 힘들다 재미 없다 즐겁지 않다 지루하다 지친다 있다 처진다 퇴사 포기 피곤 피하 하기 싫다 할수 없다 흥미 없다 힘들다
      
group3
굶다 꾸역꾸역 끼니 거르 다이어트 더부룩하다 돼지 먹어 버렸다 뚱뚱하다 마르다 많이 먹다 말랐다 모르겠다 없다 먹기 귀찮다 먹기 싫다 했다 몸무게 불었다 미식 거리 빵빵 고프다 채우다 비만 살이 붙다 살이 빠지다 살이 소화 된다 소화 불량 식욕 제어 안된다 식욕 터진다 식욕 늘다 식욕 없다 식욕 줄다 식탐 억지로 먹는다 맞지 않는다 헐렁해졌다 음식 땡긴다 없다 터졌다 입맛 늘다 먹다
      
group4
깊게 잔다 꾸벅꾸벅 졸다 눈꺼풀 무겁다 감고 있다 늦게 일어난다 다시 자기 힘들다 뒤척거린다 말똥말똥 일어나다 자다 새다 불면 불면증 새벽 깨다 수면장애 수면제 신생아 처럼 자다 얕게 자다 일찍 깨다 자고 싶다 자꾸 깬다 자다가 깨다 자도 개운하지 않다 자도 자도 피곤하다 잠들기 힘들다 자다 설친다 온다 생각 많다 졸리 통잠 못자다 못자다
      
group

# raw_docs

In [30]:
raw_vocab = []

for doc in docs:
    for w in doc.split(" "):
        raw_vocab.append(w)

raw_vocab = list(set(raw_vocab))
raw_vocab.sort()

In [31]:
from math import log

N = len(raw_docs) 

def tf(t, d):
  return d.count(t)

def idf(t):
  df = 0
  for doc in raw_docs:
    df += t in doc
  return log(N/(df+1))

def tfidf(t, d):
  return tf(t,d)* idf(t)

result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = raw_docs[i]
  for j in range(len(raw_vocab)):
    t = raw_vocab[j]
    result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = raw_vocab)

tf_

가라앉는다  가라앉다  가만있지  가망  가슴  가치  갇힌  감고  감정  감흥  ...  할수  했다  행복하지  헐렁해졌다  \
0      1     0     0   1   1   1   1   0   0   0  ...   0   0     1      0   
1      0     1     0   0   0   0   0   0   1   1  ...   1   0     0      0   
2      0     0     0   0   0   0   0   0   0   0  ...   0   1     0      1   
3      0     0     0   0   0   0   0   1   0   0  ...   0   0     0      0   
4      0     0     1   0   0   0   0   0   0   0  ...   0   0     0      0   
5      0     0     0   0   0   0   0   0   0   0  ...   0   0     0      0   
6      0     0     0   1   0   0   0   0   0   0  ...   0   0     0      0   
7      0     0     0   0   0   0   0   0   0   0  ...   0   0     0      0   
8      0     0     0   0   0   1   0   0   0   0  ...   0   0     0      0   

   헛갈리  현실  혼란  흥미  희망이  힘들다  
0    0   0   0   0    1    1  
1    0   0   0   1    0    2  
2    0   0   0   0    0    0  
3    0   0   0   0    0    2  
4    0   0   1   0    0    0  
5    0   0   0   0    0    1  
6    0   0   0   0    0    0  
7    1   0   0   0    0    3  
8    0   1   0   0    1    1  

[9 rows x 374 columns]

In [32]:
result = []
for j in range(len(raw_vocab)):
    t = raw_vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=raw_vocab, columns=["IDF"])
idf_

IDF
가라앉는다  1.504077
가라앉다   1.504077
가만있지   1.504077
가망     1.098612
가슴     1.504077
...         ...
현실     1.504077
혼란     1.504077
흥미     1.504077
희망이    1.098612
힘들다    0.251314

[374 rows x 1 columns]

In [33]:
result2 = []
for i in range(N):
  result2.append([])
  d = raw_docs[i]
  for j in range(len(raw_vocab)):
    t = raw_vocab[j]
    result2[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result2, columns = raw_vocab)
tfidf_

가라앉는다      가라앉다      가만있지        가망        가슴        가치        갇힌  \
0  1.504077  0.000000  0.000000  1.098612  1.504077  1.098612  1.504077   
1  0.000000  1.504077  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  1.504077  0.000000  0.000000  0.000000  0.000000   
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.000000  1.098612  0.000000  0.000000  0.000000   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  0.000000  0.000000  1.098612  0.000000   

         감고        감정        감흥  ...        할수        했다      행복하지     헐렁해졌다  \
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  1.504077  0.000000   
1  0.000000  1.504077  1.504077  ...  1.504077  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  ...  0.000000  1.504077  0.000000  1.504077   
3  1.504077  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
5  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
6  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
7  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

        헛갈리        현실        혼란        흥미       희망이       힘들다  
0  0.000000  0.000000  0.000000  0.000000  1.098612  0.251314  
1  0.000000  0.000000  0.000000  1.504077  0.000000  0.502629  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.502629  
4  0.000000  0.000000  1.504077  0.000000  0.000000  0.000000  
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.251314  
6  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
7  1.504077  0.000000  0.000000  0.000000  0.000000  0.753943  
8  0.000000  1.504077  0.000000  0.000000  1.098612  0.251314  

[9 rows x 374 columns]

In [82]:
tfidf_dic = tfidf_.to_dict('records')

In [84]:
tfidf_dic = tfidf_.to_dict('records')
for doc in tfidf_dic:
    for key,value in list(doc.items()):
        if value <= 1.5:
            del doc[key]

for doc in tfidf_dic:
    df = pd.DataFrame(list(doc.items()),
                   columns=['word', 'tf_idf'])
    df = df.sort_values(by=['tf_idf'], ascending=False)
    print(df)
    print("                ")
            


     word    tf_idf
9      기분  5.493061
36    아프다  3.008155
38     없다  2.010515
4      같다  1.621860
0   가라앉는다  1.504077
41   울고싶다  1.504077
30     불편  1.504077
31     불행  1.504077
32     비참  1.504077
33   센치하다  1.504077
34   속상하다  1.504077
35    슬프다  1.504077
37    안좋다  1.504077
39    외롭다  1.504077
40   우울하다  1.504077
42   울적하다  1.504077
28     별로  1.504077
43     이생  1.504077
44     잃다  1.504077
45  저주받았다  1.504077
46     절망  1.504077
47     좌절  1.504077
48     지옥  1.504077
49     체념  1.504077
50     침울  1.504077
51   캄캄하다  1.504077
52    하기도  1.504077
29   부질없다  1.504077
27     방향  1.504077
1      가슴  1.504077
14     나락  1.504077
2      갇힌  1.504077
3    갑갑하다  1.504077
5   고통스럽다  1.504077
6    공허하다  1.504077
7     괴롭다  1.504077
8     기대할  1.504077
10     까지  1.504077
11   꿀꿀하다  1.504077
12   끔찍하다  1.504077
13     끝장  1.504077
15   내려간다  1.504077
26     바닥  1.504077
16    내려갈  1.504077
17     눈물  1.504077
18     느낌  1.504077
19     다른  1.504077
20     단념  1.504077
21   답답하다  1.504077


In [ ]:
doc_idf = {}
for 

# TF-IDF(Sklearn)

In [11]:
    from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer


vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(raw_docs).toarray())

# 각 단어와 맵핑된 인덱스 출력
#print(vector.vocabulary_)

[[1 0 0 ... 1 1 0]
 [0 1 0 ... 0 2 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 1 1 0]]


In [12]:
tfidfv = TfidfVectorizer().fit(raw_docs)
print(tfidfv.transform(raw_docs).toarray())
#print(tfidfv.vocabulary_)


[[0.09812769 0.         0.         ... 0.08288021 0.05101765 0.        ]
 [0.         0.10746696 0.         ... 0.         0.11174646 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.23448239 0.        ]
 [0.         0.         0.         ... 0.07500857 0.04617219 0.        ]]


In [13]:
# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(docs).toarray())

# 각 단어와 맵핑된 인덱스 출력
print(vector.vocabulary_)

[[1 0 0 ... 0 1 1]
 [0 1 0 ... 1 0 2]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 3]
 [0 0 0 ... 0 1 1]]
{'가망': 3, '없다': 252, '가슴': 4, '아프다': 241, '가치': 5, '갇힌': 6, '같다': 11, '갑갑하다': 10, '고통스럽다': 20, '공허하다': 22, '괴롭다': 26, '기대할': 36, '기분': 37, '가라앉는다': 0, '나쁘다': 62, '별로': 170, '안좋다': 244, '처진다': 335, '꿀꿀하다': 51, '끔찍하다': 53, '끝장': 55, '나락': 58, '눈물': 78, '단념': 89, '답답하다': 91, '내려갈': 71, '마음': 121, '다른': 86, '느낌': 80, '막막하다': 124, '망하다': 131, '무의미하다': 155, '바닥': 160, '까지': 43, '내려간다': 70, '방법': 164, '방향': 165, '잃다': 277, '부질없다': 175, '불편': 182, '불행': 183, '비참': 187, '살기': 197, '싫다': 229, '생각': 204, '하기도': 355, '센치하다': 208, '속상하다': 212, '슬프다': 218, '실패': 228, '캄캄하다': 341, '외롭다': 260, '우울하다': 263, '울고싶다': 264, '울적하다': 265, '이생': 271, '저주받았다': 301, '절망': 302, '좌절': 308, '죽고': 311, '싶다': 232, '이다': 270, '지옥': 323, '체념': 336, '침울': 339, '포기': 349, '행복하지': 367, '않다': 246, '희망이': 373, '힘들다': 374, '가라앉다': 1, '감정': 8, '느껴진다': 79, '감흥': 9, '관심': 24, '줄다': 319, '귀찮다': 29, '그만두다': 32,

In [14]:
tfidfv = TfidfVectorizer().fit(docs)
print(tfidfv.transform(docs).toarray())


[[0.10096207 0.         0.         ... 0.         0.08527417 0.05249127]
 [0.         0.10765897 0.         ... 0.10765897 0.         0.11194612]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.20984708]
 [0.         0.         0.         ... 0.         0.06782747 0.0417518 ]]


In [15]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
vect = CountVectorizer()
document_term_matrix = vect.fit_transform(docs)       # 문서-단어 행렬 

tf = pd.DataFrame(document_term_matrix.toarray(), columns=vect.get_feature_names_out())
                                             # TF (Term Frequency)
D = len(tf)
df = tf.astype(bool).sum(axis=0)
idf = np.log((D+1) / (df+1)) + 1             # IDF (Inverse Document Frequency)

# TF-IDF (Term Frequency-Inverse Document Frequency)
tfidf = tf * idf                      
tfidf = tfidf / np.linalg.norm(tfidf, axis=1, keepdims=True)

tfidf =round(tfidf, 3)

tfidf

가라앉는다   가라앉다  가만있지     가망     가슴     가치     갇힌     감고     감정     감흥  ...  \
0  0.101  0.000  0.00  0.085  0.101  0.085  0.101  0.000  0.000  0.000  ...   
1  0.000  0.108  0.00  0.000  0.000  0.000  0.000  0.000  0.108  0.108  ...   
2  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
3  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.114  0.000  0.000  ...   
4  0.000  0.000  0.15  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
5  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
6  0.000  0.000  0.00  0.106  0.000  0.000  0.000  0.000  0.000  0.000  ...   
7  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
8  0.000  0.000  0.00  0.000  0.000  0.068  0.000  0.000  0.000  0.000  ...   

      할수     했다   행복하지  헐렁해졌다    헛갈리    현실    혼란     흥미    희망이    힘들다  
0  0.000  0.000  0.101  0.000  0.000  0.00  0.00  0.000  0.085  0.052  
1  0.108  0.000  0.000  0.000  0.000  0.00  0.00  0.108  0.000  0.112  
2  0.000  0.105  0.000  0.105  0.000  0.00  0.00  0.000  0.000  0.000  
3  0.000  0.000  0.000  0.000  0.000  0.00  0.00  0.000  0.000  0.119  
4  0.000  0.000  0.000  0.000  0.000  0.00  0.15  0.000  0.000  0.000  
5  0.000  0.000  0.000  0.000  0.000  0.00  0.00  0.000  0.000  0.103  
6  0.000  0.000  0.000  0.000  0.000  0.00  0.00  0.000  0.000  0.000  
7  0.000  0.000  0.000  0.000  0.135  0.00  0.00  0.000  0.000  0.210  
8  0.000  0.000  0.000  0.000  0.000  0.08  0.00  0.000  0.068  0.042  

[9 rows x 375 columns]

In [16]:
idf_df = pd.DataFrame(idf)
idf_df=idf_df.sort_values(by=0, ascending=False)


In [18]:
idf_df.head(50) # 상위 n개 행 반환

0
가라앉는다  2.609438
쓸모없다   2.609438
어깨     2.609438
얕게     2.609438
않았으면   2.609438
안좋다    2.609438
안절부절   2.609438
아프다    2.609438
아프게    2.609438
아웃     2.609438
쓸모     2.609438
없어지고   2.609438
쓰지     2.609438
쓰인다    2.609438
쓰레기    2.609438
쑤시다    2.609438
싫증     2.609438
싫어하다   2.609438
실수     2.609438
실망     2.609438
업보     2.609438
없으면    2.609438
신경질    2.609438
울적하다   2.609438
일어난다   2.609438
일어나다   2.609438
이제     2.609438
이유     2.609438
이생     2.609438
의욕     2.609438
음식     2.609438
유서     2.609438
울고싶다   2.609438
에서     2.609438
우울하다   2.609438
용서     2.609438
욕구     2.609438
외롭다    2.609438
온다     2.609438
오지     2.609438
예민     2.609438
열등감    2.609438
신생아    2.609438
식탐     2.609438
부질없다   2.609438
비만     2.609438
사라지고   2.609438
사는게    2.609438
사납다    2.609438
빵빵     2.609438

In [20]:
idf_df.tail(40)

0
한다    2.203973
피곤    2.203973
되다    2.203973
쳐지다   2.203973
느껴진다  2.203973
움직이기  2.203973
희망이   2.203973
이다    2.203973
둔하다   2.203973
있다    2.203973
억지로   2.203973
자기    2.203973
떨어지다  2.203973
가망    2.203973
않는다   2.203973
가치    2.203973
처진다   2.203973
나쁘다   2.203973
나무늘보  2.203973
실패    2.203973
나가기   2.203973
스럽다   2.203973
먹다    2.203973
지친다   2.203973
소화    2.203973
멍하다   2.203973
기분    2.203973
신경    2.203973
줄다    1.916291
같다    1.916291
난다    1.916291
안된다   1.916291
않다    1.916291
된다    1.916291
무겁다   1.693147
생각    1.693147
싶다    1.693147
싫다    1.356675
없다    1.356675
힘들다   1.356675

In [96]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
vect = CountVectorizer()
document_term_matrix = vect.fit_transform(raw_docs)       # 문서-단어 행렬 

tf = pd.DataFrame(document_term_matrix.toarray(), columns=vect.get_feature_names_out())
                                             # TF (Term Frequency)
D = len(tf)
df = tf.astype(bool).sum(axis=0)
idf = np.log((D+1) / (df+1)) + 1             # IDF (Inverse Document Frequency)

# TF-IDF (Term Frequency-Inverse Document Frequency)
tfidf = tf * idf                      
tfidf = tfidf / np.linalg.norm(tfidf, axis=1, keepdims=True)

tfidf =round(tfidf, 3)

tfidf

가라앉는다   가라앉다   가만있지   가망없다    가망이     가슴     가치    가치가     갇힌    갈리다  ...  \
0  0.098  0.000  0.000  0.000  0.098  0.098  0.098  0.000  0.098  0.000  ...   
1  0.000  0.107  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
2  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
3  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
4  0.000  0.000  0.143  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
5  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.178  ...   
6  0.000  0.000  0.000  0.075  0.000  0.000  0.000  0.000  0.000  0.000  ...   
7  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000  ...   
8  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.089  0.000  0.000  ...   

    행복하지  헐렁해졌다  헛갈리다   현실도피  혼란스럽다     회가     흥미    희망이    힘들다     힘이  
0  0.098  0.000  0.00  0.000  0.000  0.000  0.000  0.083  0.051  0.000  
1  0.000  0.000  0.00  0.000  0.000  0.000  0.107  0.000  0.112  0.000  
2  0.000  0.107  0.00  0.000  0.000  0.000  0.000  0.000  0.000  0.000  
3  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.000  0.119  0.000  
4  0.000  0.000  0.00  0.000  0.143  0.000  0.000  0.000  0.000  0.000  
5  0.000  0.000  0.00  0.000  0.000  0.000  0.000  0.000  0.093  0.178  
6  0.000  0.000  0.00  0.000  0.000  0.075  0.000  0.000  0.000  0.000  
7  0.000  0.000  0.15  0.000  0.000  0.000  0.000  0.000  0.234  0.000  
8  0.000  0.000  0.00  0.089  0.000  0.000  0.000  0.075  0.046  0.000  

[9 rows x 431 columns]

In [97]:
idf_df = pd.DataFrame(idf)
idf_df=idf_df.sort_values(by=0, ascending=False)



In [98]:
idf_df.head(20)

0
가라앉는다  2.609438
안나오다   2.609438
업보     2.609438
어둔하다   2.609438
어깨가    2.609438
얕게     2.609438
약을     2.609438
앞이     2.609438
않았으면   2.609438
안좋다    2.609438
안절부절   2.609438
안온다    2.609438
아프다    2.609438
없으면    2.609438
아프게    2.609438
쓸모없다   2.609438
쓰지     2.609438
쓰레기    2.609438
쑤시다    2.609438
싫증     2.609438

In [99]:
idf_df.tail(20)

0
지친다  2.203973
나쁘다  2.203973
멍하다  2.203973
않는다  2.203973
둔하다  2.203973
난다   2.203973
소화가  2.203973
처진다  2.203973
기분이  2.203973
귀찮다  2.203973
된다   1.916291
않다   1.916291
안된다  1.916291
몸이   1.916291
줄다   1.916291
무겁다  1.693147
싶다   1.693147
없다   1.510826
힘들다  1.356675
싫다   1.356675